name: Android CI

on:
  push:
    branches: [ feature/week4_changik ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./최창익

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}
    - name: 헬로월드 찍어보기
      run: echo "Hello World"
      working-directory: ${{ env.working-directory }}
